// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Prashant Agrawal",
            "email": "prashant.eee.nitt@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/robot/tasks": {
            "post": {
                "description": "Add a new robot task with commands and optional delay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Robot Tasks"
                ],
                "summary": "Add a new robot task",
                "parameters": [
                    {
                        "description": "Add Task Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AddTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Task ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AddTaskRequest": {
            "description": "Request body for adding a new robot task",
            "type": "object",
            "required": [
                "commands"
            ],
            "properties": {
                "commands": {
                    "description": "Commands to be executed by the robot",
                    "type": "string",
                    "example": "N E S W"
                },
                "delay_between_commands": {
                    "description": "Delay between executing commands, optional",
                    "type": "string",
                    "example": "1s"
                }
            }
        },
        "api.ErrorResponse": {
            "description": "Generic error response.",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Job not found"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Robot Warehouse System",
	Description:      "This is a REST API for managing robot tasks in a warehouse system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
