name: Robot Warehouse CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Lint
        run: go vet ./...

      - name: Build
        run: go build ./...

      - name: Run Tests
        run: go test ./... -v